version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001" # For RedisStack GUI (optional)
    environment:
      - REDIS_ARGS=--requirepass pingpong
    command: sh -c "redis-stack-server $REDIS_ARGS"
    restart: unless-stopped